export {
  sendMessage,
  sendRichMessage,
  editMessage,
  editRichMessage,
  editMessageReplyMarkup,
  sendPhoto,
  sendDocument,
  sendVoice,
  sendChatAction,
  answerCallbackQuery,
  deleteMessage,
  splitForTelegram,
  editLongMessage,
  verifySecret,
  escapeHtml,
  escapeMarkdownV2,
  setMyCommands,
  getTelegramFileUrl,
  downloadTelegramFile,
  convertNewlinesToBr,
} from '@cal/telegram';

export type {
  ParseMode,
  SendMessageOpts,
  SendRichMessageOpts,
  ChatAction,
  BotCommand,
  TelegramVoice,
  TelegramPhotoSize,
  TelegramReactionType,
  TelegramMessageReaction,
} from '@cal/telegram';
