name = "spotify-auth"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
SPOTIFY_REDIRECT_URI = "https://spotify-auth.carlos-cb4.workers.dev/callback"

[[kv_namespaces]]
binding = "SPOTIFY_TOKENS"
id = "48ced0405e5447169456904a3684d46b"
